### ISSUE TITLE
missing bemto.pug breaks yarn dev

### ISSUE THREAD

**Issue by th0rgall** [louisbarclay/nudge#123]
'src/bemto/bemto.pug' is not committed to this repository, but is referenced many times in other `.pug` files (for example https://github.com/louisbarclay/nudge/blob/master/src/pug/injected/hider-menu.pug#L1)

This results in errors of the following type when running `yarn dev`:

```
Error: ENOENT: no such file or directory, open 'src/bemto/bemto.pug'
    at src/pug/injected/other/hider-menu-alt.pug line 1
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Function.read (/Users/thor/Code/contrib/nudge/node_modules/pug-load/index.js:69:13)
    at Object.read (/Users/thor/Code/contrib/nudge/node_modules/pug/lib/index.js:147:25)
    at /Users/thor/Code/contrib/nudge/node_modules/pug-load/index.js:24:25
    at walkAST (/Users/thor/Code/contrib/nudge/node_modules/pug-walk/index.js:23:18)
    at /Users/thor/Code/contrib/nudge/node_modules/pug-walk/index.js:104:20
    at Array.reduce (<anonymous>)
    at walkAndMergeNodes (/Users/thor/Code/contrib/nudge/node_modules/pug-walk/index.js:103:18)
    at walkAST (/Users/thor/Code/contrib/nudge/node_modules/pug-walk/index.js:37:19)
```

**Comment by louisbarclay** [comment]
This should be fixed by https://github.com/louisbarclay/nudge/commit/b4a3a99711113f9d4f39516f66b6d9e6310289bf
